### ISSUE TITLE
#US38 - Afficher les articles dans une langue

### ISSUE THREAD

**Issue by johangiraud** [cafebabel/cafebabel.com#221]
ETQ lectrice je souhaite changer la langue de consultation afin de changer de pays

- [x] - devrait positionner la langue de consultation par défaut en détectant la langue du navigateur
- [x] - devrait afficher la traduction de l'article courant quand je change la langue de consultation https://github.com/cafebabel/cafebabel.com/issues/290
- [x] - pourrait rediriger les catégories vers la page catégorie correspondante #297
- [x] - doit afficher la home quand on ne peut pas afficher de traduction https://github.com/cafebabel/cafebabel.com/issues/290
- [x] - doit faire pointer le logo Café Babel - (header) - sur la langue de consultation https://github.com/cafebabel/cafebabel.com/issues/291
- [x] - doit faire pointer les réseaux sociaux dans le -header- vers les langues correspondantes #293
- [x] - doit proposer la langue de consultation comme -langue- par défaut, lors de la création ou la suggestion d'un article #294
- [x] - ne doit pas permettre le changement de langue une fois que l'article a été sauvegardé #294

**Comment by davidbgk** [comment]
I think this is a duplicate of https://github.com/cafebabel/cafebabel.com/issues/214

**Comment by johangiraud** [comment]
En fait, on a va baisser le niveau d'attente pour la mise en ligne le site. Du coup je change le plan de release. Pour la traduction du site on va juste faire un bouton de switch de langue qui affiche les articles dans une langue ou dans l'autre. On ne va pas traduire l'interface finalement @davidbgk

**Comment by pointbar** [comment]
#341 - Le TA sur les liens des réseaux contextualisé par langue ne semble pas fonctionné
